development:
  clients:
    default:
      database: inova_cluster
      hosts:
        - 30003:27017

test:
  clients:
    default:
      database: inovamind_test
      hosts:
        - 30003:27017

production:
  sessions:
    default:
      database: inova_cluster
        hosts:
          - 30003:27017